### ISSUE TITLE
Training scripts for CIFAR-10

### ISSUE THREAD

**Issue by GongXinyuu** [akanimax/BMSG-GAN#15]
Hi Akanimax, thanks for your great work!

Could you please also release the training scripts for CIFAR10 generation?

**Comment by akanimax** [comment]
@GongXinyuu, 
I have added the pytorch datasets options in this branch -> [cifar_script](https://github.com/akanimax/BMSG-GAN/tree/cifar_script). Please use the `--pytorch_dataset=cifar-10 --dataset_dir=../data/cifar-10/` options for training on the CIFAR-10 dataset. I'll add it to master later.

Hope it helps.

Best regards,
@akanimax

**Comment by GongXinyuu** [comment]
Thank you very much!
