### ISSUE TITLE
How much GPU memory to use for 1024*1024?

### ISSUE THREAD

**Issue by wodsoe** [akanimax/BMSG-GAN#17]
How much GPU memory to use for 1024*1024?

**Comment by robbiebarrat** [comment]
bumping this- i have the same question

**Comment by robbiebarrat** [comment]
@wodsoe i just tried it out; not sure exactly but more than 12gb it seems. it's stated that they used v100s (16gb gpus) - so the full 1024x1024 model is somewhere between 12 and 16 gb

**Comment by wodsoe** [comment]
@robbiebarrat Thank you!So it doesn't work on 1080ti or 2080ti.

**Comment by akanimax** [comment]
@wodsoe, @robbiebarrat.
That is a little unlikely. Do you mean that on your GPU, even a batch size of 1 doesn't fit?

**Comment by powerspowers** [comment]
I think that this code would have to be updated to use mixed precision floating point for a 1080 or 2080 to be able to handle 1024x1024. I started to modify their newer BBMSGAN to try to add nVidia's code for fp16. My coding skills are definitely getting stretched. Going mixed precision would effectively double what GPU memory could handle.
