### ISSUE TITLE
Data preprocessing tips

### ISSUE THREAD

**Issue by hbarovertwo** [akanimax/BMSG-GAN#19]
Hello @akanimax , awesome results.

I have my own use case which is generate realistic images of vehicles. 
I am using a publicly available dataset for testing, I think stanford cars dataset.

I am wondering how important alignment is. For example if I have cars in different orientation (facing left, right etc) should I make them all aligned for the GAN training? If I don't, will this hinder the ability to generate images?

Thanks for any insight, 
Mason

**Comment by akanimax** [comment]
@hbarovertwo,

The MSG-GAN technique is quite robust to such variations in the input images. To give you an example, the flowers shown on the README were only resized to `256 x 256` no other kind of cropping / alignment was done. Besides this, I have also trained it on a completely unaligned dataset (open Image dataset) with good results. I also remember @BlindElephants had trained on a dataset extracted from a movie. I would highly encourage you to train without spending too much effort on aligning the dataset. 

Hope this helps.

Cheers!
@akanimax

**Comment by hbarovertwo** [comment]
Thanks!! Running an iteration now and will see how it goes!
