### ISSUE TITLE
Starting point to add conditioning on labels?

### ISSUE THREAD

**Issue by hbarovertwo** [akanimax/BMSG-GAN#20]
Sorry @akanimax to open a new issue but this is a question I would love some help with. Basically I want to modify your architecture slightly to add the functionality of conditioning on image labels. For example if training on the flowers set, rather than just load image data to the model, load both image data + accompanying image label data like image of sunflower and label like tall yellow flower, black seeds in middle etc.

Can you give me an idea of how to start with this with your code?
My plan to generate labels is use subfolders in image set where each subfolder name contains images of that name. 

Thanks again,
Mason

**Comment by akanimax** [comment]
@hbarovertwo,
Thanks for your issue (why sorry? :smile:).  Our research was mainly focused on the unconditional setting of Image generation so, we never added the conditional settings to this code. 
But, please refer to the this portion of my `pro_gan_pytorch` code -> [here](https://github.com/akanimax/pro_gan_pytorch/blob/master/pro_gan_pytorch/PRO_GAN.py#L213)
This might be helpful for you to code it. The BMSG-GAN code was written using the `pro_gan_pytorch` as the base code. 

Also note that this version (`pro_gan_pytorch`) assumes scalar labels and uses the projection mechanism for modeling the conditional information. You'd probably have to use the concatenation based mechanism for vector conditioning labels. 

Hope this helps.

Please feel free to ask if you have any other questions.

Cheers :beers:!
@akanimax

**Comment by hbarovertwo** [comment]
Thanks for the help! Mainly if I can figure out a solution that scales, that will be great. I will let you know when I run into more questions about it. And I am using your latest release, BBMSG-GAN :)

**Comment by akanimax** [comment]
There hasn't been any activity here for a long time.
So, closing this issue. Please feel free to comment if there are any problems :+1:
