### ISSUE TITLE
I want to just test the discriminator of this GAN using my abnormal images.

### ISSUE THREAD

**Issue by bemoregt** [akanimax/BMSG-GAN#21]
Hi, @markstrefford @owang @sridharmahadevan @akanimax @huangzh13 

I trained successfully anomalyGAN with your MSG-GAN using my only normal images.

And now , I want to just test the discriminator of this GAN using my abnormal images...

How can I extract the discriminator from your MSG-GAN ?

Thanks in advance.

Best,
@bemoregt.

**Comment by markstrefford** [comment]
You could modify this script... 
https://github.com/akanimax/BMSG-GAN/blob/master/sourcecode/demo.py

**Comment by akanimax** [comment]
Hope this is solved...
Closing :smile:
