### ISSUE TITLE
Reproduction on another dataset

### ISSUE THREAD

**Issue by TropComplique** [akanimax/BMSG-GAN#23]
Hi!
I like your paper.

Here is my version of your algorithm trained to generate dresses:
https://github.com/TropComplique/multi-scale-gradient-gan.

But I made some modifications: 
1. I use self modulation (stylegan-like generator),
2. I use R1 penalty for discriminator,
3. I use PacGAN discriminator.

**Comment by akanimax** [comment]
@TropComplique!
Thanks a lot for sharing your implementation :smile:. I have starred :star: your repo!
Your results on the dresses dataset are nice. I find it cool that you used the styleGAN architecture with MSG-GAN. 

Even I am working on something very similar ... :smile:.
Here is a small teaser of what is coming ...

![celebahq_towers_1](https://user-images.githubusercontent.com/16590868/68404374-bb69c680-017e-11ea-94b8-f0bae2f9231b.png)
![ffhq_towers_4](https://user-images.githubusercontent.com/16590868/68404386-bf95e400-017e-11ea-9891-7627e69ff087.png)

Will be releasing this code soon.

Cheers :beers:!
@akanimax

**Comment by TropComplique** [comment]
The teaser looks very delightful.
And thanks for your good work.
