### ISSUE TITLE
what is flower dataset

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/BMSG-GAN#24]
Hi, Would supply the flower dataset link ??

**Comment by akanimax** [comment]
@Johnson-yue,
It's a quite commonly used dataset called Oxford 102 Flowers dataset. 
This is the link to the dataset -> [https://www.robots.ox.ac.uk/~vgg/data/flowers/102/](https://www.robots.ox.ac.uk/~vgg/data/flowers/102/)
Hope this helps :smile: 

Cheers :beers:!
@akanimax

**Comment by Johnson-yue** [comment]
I do not have so many GPU， so， I only can use small dataset to test （I only have one RTX 2080ti），thank you， I will train it with your network

**Comment by akanimax** [comment]
Wow! RTX. I have not had the chance to get a hands on it yet :smile:. Please let me know how you find the performance. BTW, I am soon going to release my MSG-StyleGAN code. Stay tuned. Perhaps you could give that one a try. It has really nice performance.
![Oxford_flowers](https://user-images.githubusercontent.com/16590868/69524725-064d5180-0f67-11ea-8e35-f4153513f379.png)
These are my latest flowers results. :smile: 

Hope this helps.

Cheers :beers:!
@akanimax

**Comment by Johnson-yue** [comment]
Hi， I have downloaded the flower-102 dataset， and it only have 8189 pictures。 something I missing？？ or your network can be train with only 8k images and get so good performance？

If I want to training flower dataset , Would you supply a train script ? like using eql or not? using ema or not ? Although  I think them should be used, anyway

**Comment by akanimax** [comment]
Oh yeah, the dataset does have only 8K images. The MSG-GAN method works quite well on datasets of small sizes too. We obtained a record FID of **19.6082** with the latest method. 
But this version also has a score of around **~30** I guess.

**Comment by Johnson-yue** [comment]
Wow， the new method is MSG-styleGAN？ brilliant！ 
but now ， I think test this version first，how many epoch will be train with flowers？

**Comment by Johnson-yue** [comment]
500 epoch train result:
![gen_539_125](https://user-images.githubusercontent.com/10268274/70108859-43ab9080-1685-11ea-97fd-a8559077822b.png)

128x128 with flowers-102 dataset , very nice !! I will test other dataset , thank you

**Comment by Johnson-yue** [comment]
500 epoch train result:
![gen_539_125](https://user-images.githubusercontent.com/10268274/70108859-43ab9080-1685-11ea-97fd-a8559077822b.png)

128x128 with flowers-102 dataset , very nice !! I will test other dataset , thank you
