### ISSUE TITLE
How to quick test for trained model

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/BMSG-GAN#26]
Hi, I have train the MSG-GAN model with flower-102 dataset, and I have trained model weight.
So,  how can I quick test this model to generate same flower from noise ??

Will I write load network and generate code ?? or you have this code but Not show then in **ReadMe**

Would you update **ReadMe** about how to test ?? this is better for use, thank you

**Comment by akanimax** [comment]
@Johnson-yue,

You can use the [demo.py](https://github.com/akanimax/BMSG-GAN/blob/master/sourcecode/demo.py) for this. Hope this helps.

Best regards,
@akanimax

**Comment by Johnson-yue** [comment]
Thank，I try it later
