### ISSUE TITLE
How importance about **Equalized learning rate**

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/BMSG-GAN#27]
Hi， as I know this trick start with StyleGAN， but I not train GAN successful with it，I see， you also recommend it， So， I want to ask， how importance about **eql** with your feeling

**Comment by akanimax** [comment]
Yeah, from my experience, the equalized learning rate helps a lot :+1:.

**Comment by Johnson-yue** [comment]
ok，thank you for your experience， it also helps me a lot
