### ISSUE TITLE
When you update this repo with styleGAN

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/BMSG-GAN#28]
Hi， I have test different dataset by using BMSG-GAN， and it work well，so can I ask when you will update this repo to the latest one ??

**Comment by akanimax** [comment]
@Johnson-yue,
The new repo is available at -> [https://github.com/akanimax/msg-stylegan-tf](https://github.com/akanimax/msg-stylegan-tf).
The code is in tensorflow.
Hope this helps :+1:
