### ISSUE TITLE
Sagemaker config

### ISSUE THREAD

**Issue by markstrefford** [akanimax/BMSG-GAN#6]
Hi, I've added config to allow this to run on AWS SageMaker here:
https://github.com/markstrefford/Sagemaker-BMSG-GAN/
Do you want a PR for this?

**Comment by akanimax** [comment]
@markstrefford,

Thanks a lot. This will be beneficial to those using AWS sagemaker for their training. Please feel free to open a PR, I am always open for contributions.
Thanks again.

Best regards,
@akanimax

**Comment by akanimax** [comment]
@markstrefford 
Thanks for the pull request.

Cheers :beers:!
@akanimax
